In [1]:
import sys
sys.path.append('/Users/spacecoffin/Development')

import GravelKicker as gk
import librosa
import matplotlib.pyplot as plt
import numpy as np
import os
import pandas as pd
import sklearn as sk

from datetime import datetime
from supriya.tools import nonrealtimetools

%matplotlib inline

In [2]:
this_dir = '/Users/spacecoffin/Development/GravelKicker/__gen_files'

# Loading utility

Add: join old df to new df

In [ ]:
dir_list = os.listdir(path=this_dir)
_pickle_path = os.path.join(this_dir, "df.p")

if "df.p" in dir_list:
    #_pickle_path = os.path.join(this_dir, "df.p")
    _old_df = pd.read_pickle(_pickle_path)
    _pickle_dir = make_out_dir(this_dir, "pickle_files")
    dt_identifier = datetime.now().strftime("df-%Y_%m_%d_%H%M%S.p")
    _old_pickle_path = os.path.join(_pickle_dir, dt_identifier)
    pd.to_pickle(_old_pickle_path)

    

In [3]:
pmtx = gk.generator.gendy1.gen_params(dists=(0., 0.), rows=100)

In [4]:
df = gk.generator.gendy1.format_params(pmtx)

In [5]:
df

adparam  ampscale   ddparam  durscale  ampdist  durdist  knum  \
0   0.635286  0.489605  0.567881  0.369180      0.0      0.0  10.0   
1   0.696958  0.800929  0.685938  0.171620      0.0      0.0  14.0   
2   0.429322  0.360878  0.995214  0.278283      0.0      0.0  11.0   
3   0.653165  0.266634  0.949110  0.821236      0.0      0.0  14.0   
4   0.714823  0.079651  0.797190  0.961920      0.0      0.0  11.0   
5   0.811914  0.929303  0.444593  0.715531      0.0      0.0  14.0   
6   0.585464  0.433918  0.976519  0.932159      0.0      0.0  12.0   
7   0.818929  0.125319  0.168451  0.464151      0.0      0.0  10.0   
8   0.533845  0.666820  0.586361  0.163195      0.0      0.0  12.0   
9   0.859485  0.380770  0.747093  0.868054      0.0      0.0  12.0   
10  0.556470  0.600817  0.674834  0.855629      0.0      0.0  12.0   
11  0.493465  0.100789  0.956789  0.636812      0.0      0.0   9.0   
12  0.931189  0.142806  0.012430  0.617764      0.0      0.0  13.0   
13  0.704062  0.070166  0.208522  0.143551      0.0      0.0  16.0   
14  0.247245  0.470690  0.509268  0.706318      0.0      0.0  14.0   
15  0.007715  0.859809  0.416540  0.376740      0.0      0.0  10.0   
16  0.480551  0.422815  0.035301  0.373041      0.0      0.0  12.0   
17  0.557386  0.916642  0.777535  0.607154      0.0      0.0   8.0   
18  0.400411  0.580839  0.066132  0.061830      0.0      0.0  12.0   
19  0.724139  0.625939  0.150455  0.146902      0.0      0.0  12.0   
20  0.483189  0.379642  0.929342  0.963592      0.0      0.0  12.0   
21  0.008176  0.635240  0.330755  0.215888      0.0      0.0   9.0   
22  0.277841  0.840331  0.042573  0.653451      0.0      0.0  10.0   
23  0.065132  0.846646  0.828625  0.951987      0.0      0.0  11.0   
24  0.946532  0.696673  0.621477  0.046002      0.0      0.0   8.0   
25  0.202591  0.853369  0.690199  0.828766      0.0      0.0  14.0   
26  0.359538  0.090099  0.025959  0.715595      0.0      0.0  13.0   
27  0.252558  0.870870  0.726149  0.269884      0.0      0.0  12.0   
28  0.997314  0.620051  0.016455  0.900552      0.0      0.0  11.0   
29  0.586763  0.625249  0.096503  0.671703      0.0      0.0  13.0   
..       ...       ...       ...       ...      ...      ...   ...   
70  0.026503  0.493471  0.360334  0.993795      0.0      0.0  11.0   
71  0.619612  0.021298  0.988322  0.548706      0.0      0.0  13.0   
72  0.771522  0.575452  0.896984  0.971402      0.0      0.0  12.0   
73  0.593228  0.626976  0.767520  0.333170      0.0      0.0  11.0   
74  0.545711  0.146602  0.241695  0.242677      0.0      0.0  10.0   
75  0.153862  0.758355  0.253736  0.544259      0.0      0.0  10.0   
76  0.730071  0.829273  0.068024  0.366864      0.0      0.0  12.0   
77  0.270129  0.498033  0.313730  0.356321      0.0      0.0  11.0   
78  0.618356  0.170198  0.733218  0.337764      0.0      0.0  10.0   
79  0.130412  0.567207  0.591310  0.259960      0.0      0.0  12.0   
80  0.199951  0.848940  0.410141  0.576346      0.0      0.0  10.0   
81  0.340358  0.248305  0.670087  0.416224      0.0      0.0  14.0   
82  0.752289  0.090410  0.201556  0.341861      0.0      0.0  13.0   
83  0.576293  0.789588  0.293744  0.032759      0.0      0.0  11.0   
84  0.769568  0.356891  0.091411  0.754923      0.0      0.0  13.0   
85  0.913810  0.883568  0.054602  0.976367      0.0      0.0   8.0   
86  0.151999  0.747931  0.715174  0.317170      0.0      0.0  11.0   
87  0.918004  0.173537  0.798004  0.254347      0.0      0.0  11.0   
88  0.665568  0.079789  0.635287  0.736320      0.0      0.0  12.0   
89  0.235003  0.781408  0.396755  0.086148      0.0      0.0  11.0   
90  0.627859  0.631454  0.904592  0.526539      0.0      0.0  12.0   
91  0.284942  0.740700  0.233742  0.316137      0.0      0.0  12.0   
92  0.655543  0.048233  0.188027  0.529587      0.0      0.0  12.0   
93  0.480733  0.229740  0.677456  0.286135      0.0      0.0   8.0   
94  0.969128  0.342286  0.983257  0.433680      0.0      0.0  16.0   
95  0.197262  0

In [30]:
pmtx

array([[  1.40566725e-01,   2.96348706e-01,   6.94119437e-01,
          8.70139674e-01,   5.00000000e+00,   5.00000000e+00,
          1.20000000e+01,   2.75000000e+01,   1.23470825e+02,
          1.60000000e+01],
       [  9.76231054e-01,   2.77556017e-01,   6.17027301e-01,
          1.73149196e-01,   5.00000000e+00,   5.00000000e+00,
          1.10000000e+01,   1.63515978e+01,   2.59565436e+01,
          1.60000000e+01],
       [  6.39036413e-01,   7.79432295e-01,   9.54356368e-01,
          2.48040346e-01,   5.00000000e+00,   0.00000000e+00,
          1.40000000e+01,   2.20000000e+02,   9.32327523e+02,
          1.60000000e+01],
       [  8.56777788e-01,   6.15597540e-01,   1.14462311e-01,
          8.65524238e-01,   2.00000000e+00,   2.00000000e+00,
          1.00000000e+01,   4.15304698e+02,   1.97553321e+03,
          1.60000000e+01],
       [  7.17413492e-01,   8.86676141e-01,   4.46664321e-01,
          4.29449566e-01,   0.00000000e+00,   5.00000000e+00,
          1.40000000e+01

### Generation/rendering timing

~$0.189$ seconds per example/`.aiff`.

*18.9s for 100*

In [8]:
%time

for i, row in df.iterrows():
    
    session = nonrealtimetools.Session()
    
    builder = gk.generator.gendy1.make_builder(row)
    
    out = gk.generator.gendy1.build_out(builder)
    
    synthdef = builder.build()
    
    with session.at(0):
        synth_a = session.add_synth(duration=10, synthdef=synthdef)
    
    gk.util.render_session(session, this_dir, row["hash"])

1 loop, best of 3: 18.9 s per loop


### Feature extraction timing

~$0.88$ seconds per example/`.aiff`.

*1m 28s for 100*

In [10]:
%timeit

for i, row in df.iterrows():
    
    y, sr = librosa.load(os.path.join(this_dir, "aif_files", row["hash"] + ".aiff"))
    
    _y_normed = librosa.util.normalize(y)
    _mfcc = librosa.feature.mfcc(y=_y_normed, sr=sr, n_mfcc=13)
    _cent = np.mean(librosa.feature.spectral_centroid(y=_y_normed, sr=sr))
    
    _mfcc_mean = gk.feature_extraction.get_stats(_mfcc)["mean"]
    
    X_row = np.append(_mfcc_mean, _cent)
    
    if i==0:
        X_mtx = X_row
    else:
        X_mtx = np.vstack((X_mtx, X_row))

1 loop, best of 3: 1min 28s per loop


**Thought**: For *feature extraction*, it would probably be faster to extract all time domain vectors $y$ into a `NumPy` array and perform the necessary `LibROSA` operations across the rows of the vector, possibly leveraging under-the-hood efficiencies. 

`"1min 43s per loop"` below

In [13]:
for i, row in df.iterrows():
    
    session = nonrealtimetools.Session()
    
    builder = gk.generator.gendy1.make_builder(row)
    
    out = gk.generator.gendy1.build_out(builder)
    
    synthdef = builder.build()
    
    with session.at(0):
        synth_a = session.add_synth(duration=10, synthdef=synthdef)
    
    gk.util.render_session(session, this_dir, row["hash"])
    
    y, sr = librosa.load(os.path.join(this_dir, "aif_files", row["hash"] + ".aiff"))
    
    _y_normed = librosa.util.normalize(y)
    _mfcc = librosa.feature.mfcc(y=_y_normed, sr=sr, n_mfcc=13)
    _cent = np.mean(librosa.feature.spectral_centroid(y=_y_normed, sr=sr))
    
    _mfcc_mean = gk.feature_extraction.get_stats(_mfcc)["mean"]
    
    X_row = np.append(_mfcc_mean, _cent)
    
    if i==0:
        X_mtx = X_row
    else:
        X_mtx = np.vstack((X_mtx, X_row))

1 loop, best of 3: 1min 43s per loop


In [16]:
X_mtx.shape

(100, 14)

In [20]:
def col_rename_4_mfcc(c):
    if (c < 13):
        return "mfcc_mean_{}".format(c)
    else:
        return "spectral_centroid"

In [21]:
pd.DataFrame(X_mtx).rename_axis(lambda c: col_rename_4_mfcc(c), axis=1)

mfcc_mean_0  mfcc_mean_1  mfcc_mean_2  mfcc_mean_3  mfcc_mean_4  \
0   -130.944498   212.246248    22.733654    40.690030    12.067444   
1   -399.895787   110.209896    74.756361    45.275353    30.022552   
2     91.596323    84.458611   -51.472184    22.995390   -13.212321   
3    108.614834    41.703153   -43.736769    12.669656   -12.150096   
4   -257.498754   196.193063    51.860213    33.223307    34.137235   
5   -193.675721   200.459160     9.867697    17.697053    -1.148573   
6    -99.255339   187.928813    -2.400399    14.618994   -13.758809   
7    -65.096548   119.754086   -35.833374   -13.031844   -13.445218   
8   -150.207907   199.412785    22.935211    46.877748    22.706417   
9   -149.157050   210.391977    22.183814    42.031267    18.932379   
10  -340.201357   165.930251    70.565247    30.761530    31.261373   
11     6.112265   148.653894   -38.904657    15.262946     0.279633   
12    -6.867327   175.536196    -8.756827    -0.813062   -25.938709   
13  -273.189933   196.842472    44.006941    32.859688    30.937577   
14    -1.179280   186.504575   -13.168122     7.702715    -6.959950   
15     4.551287   136.437145   -51.754995    -7.027945    -4.988497   
16    85.181769   119.017278   -55.916597    12.750346    -6.694964   
17    90.191236    14.656168   -47.594906     5.551048   -17.733038   
18   -83.394020   187.360281    20.232888    38.943839    -4.743480   
19   -73.318825   171.378497   -22.353387    -1.984178    -8.114975   
20    18.196390    36.265611   -57.300253    34.892149   -22.674767   
21  -202.216136   209.230301    34.720954    38.528029    26.253699   
22  -313.176685   155.511469    73.811454    32.795860    29.677764   
23    -9.615172   129.716910   -52.212949    -1.136605    13.376242   
24  -259.514615   185.040826    59.646164    30.595194    34.250743   
25   -35.086315   136.811693   -32.048640    -8.674571   -17.973700   
26     2.140036    22.958742   -61.243439    31.232914   -18.617048   
27  -180.303722   210.031939    25.614925    42.866791    21.707217   
28   109.403837    69.055065   -16.386115    14.482498    -7.015294   
29  -105.319927   188.452663    -9.875766     9.693579    -1.902148   
..          ...          ...          ...          ...          ...   
70  -307.813300   171.501835    43.073483     1.186148   -17.059571   
71  -256.262220   177.667570    35.279755    41.074118    32.646052   
72  -123.638507   196.101218    16.091192    37.703966     8.586197   
73    91.201402    61.890904   -50.296706    34.611358   -19.843078   
74    61.521574    75.549878   -70.206479     4.072889   -12.268407   
75  -348.854984   131.896991    77.298459    38.691859    27.370018   
76    -3.951955   175.926868   -16.887992     2.177106   -21.221609   
77     6.312709    64.119320     0.662811    20.428846     2.098026   
78  -265.967826   189.684948    40.921330    28.918336     3.856197   
79   114.066912    65.705402   -13.982049    15.738120    -2.697014   
80    52.080801    -2.029646    -9.214531    16.661814    14.812910   
81     0.129542     1.296577     1.134177    29.180047    16.657870   
82    50.185707    69.750195   -62.128786    31.666168   -12.838869   
83  -141.369083   200.989763    22.828728    47.725317    23.799062   
84   -33.911887   177.238500     1.460917    -1.179384   -29.288186   
85    95.620136    24.162909   -21.330590    12.638309    -5.323904   
86   -78.124385   180.139992     1.803036    26.684432   -10.907147   
87  -102.630029   208.396622    18.649455    38.064037     7.297848   
88    36.237315    81.456456   -68.728021     6.888781     0.927624   
89   -13.889859   152.856319   -21.261154   -13.211758   -10.707592   
90    83.447113     1.812704     4.520221    28.265909    15.011482   
91  -185.604592   206.337093    25.511371    45.913118    24.236532   
92   106.618408    68.227289   -35.364793    11.350113   -13.695992   
93  -413.286972   103.664304    74.358332    46.970740    31.255063   
94    45.976830   -14.512710

In [66]:
pmtx.shape

(100, 10)

In [67]:
X_mtx.shape

(100, 14)

In [68]:
X_mtx[0]

array([ -1.30944498e+02,   2.12246248e+02,   2.27336540e+01,
         4.06900302e+01,   1.20674442e+01,   1.15757863e+01,
        -2.92309292e+00,   1.96352599e+00,   1.01233809e+00,
         5.04106581e+00,  -1.77814489e+00,  -5.92080878e-02,
        -5.38241320e-02,   4.39129383e+02])

In [31]:
X_train, X_test, y_train, y_test = sk.model_selection.train_test_split(
    X_mtx, pmtx, test_size=0.4, random_state=1)

In [38]:
# Create linear regression objectc
regr = linear_model.LinearRegression()

# Train the model using the training sets
regr.fit(X_train, y_train)

# The coefficients
print('Coefficients: \n', regr.coef_)
# The mean squared error
print("Mean squared error: %.2f"
      % np.mean((regr.predict(X_test) - y_test) ** 2))
# Explained variance score: 1 is perfect prediction
print('Variance score: %.2f' % regr.score(X_test, y_test))

Coefficients: 
 [[ -7.64326344e-04   5.43840972e-04   8.33835578e-04  -1.63296951e-03
    1.84396630e-03  -1.63494109e-03  -4.13973644e-03   9.93769874e-03
   -1.21937858e-02   1.07145282e-02  -3.50315085e-03   8.43229154e-03
    5.97796792e-03   7.19034767e-05]
 [  4.14076160e-03   1.49650267e-03   7.37848988e-03  -5.89920432e-03
    6.43978853e-03   2.56377513e-03   5.08002799e-03   6.34448830e-03
    2.48995221e-03  -9.09774452e-04   3.85030377e-03   1.95772826e-03
    1.02450172e-02  -8.23419500e-05]
 [ -1.58993713e-03   2.26292332e-03  -2.75211523e-03   7.45264689e-03
   -9.26048513e-04  -1.65945356e-03  -4.77375839e-03   1.51891806e-02
   -1.34561050e-02   1.02081968e-02  -5.44665508e-03   1.38347150e-02
   -1.23215340e-02   1.37929495e-04]
 [  7.85798120e-04   2.41554881e-03   1.78210384e-03  -9.60912755e-04
   -5.29459040e-03   3.47813067e-03  -1.96233126e-03   2.84434039e-03
    1.35618930e-03  -1.21362974e-03   2.00095401e-03   1.95225907e-03
    7.85679139e-03   4.24680697e-

/Users/spacecoffin/Development/sprbrg/lib/python3.5/site-packages/scipy/linalg/basic.py:884: RuntimeWarning: internal gelsd driver lwork query error, required iwork dimension not returned. This is likely the result of LAPACK bug 0038, fixed in LAPACK 3.2.2 (released July 21, 2010). Falling back to 'gelss' driver.
  warnings.warn(mesg, RuntimeWarning)


# Preprocessing

In [42]:
# Scale data
standard_scaler = sk.preprocessing.StandardScaler()
X_scaled = standard_scaler.fit_transform(X_mtx)
#Xte_s = standard_scaler.transform(X_test)

robust_scaler = sk.preprocessing.RobustScaler()
X_rscaled = robust_scaler.fit_transform(X_mtx)
#Xte_r = robust_scaler.transform(X_test)

In [57]:
X_scaled.mean(axis=0)

array([  2.95319325e-16,   1.93178806e-16,   3.21964677e-17,
        -5.66213743e-17,  -6.66133815e-18,   3.96696564e-16,
         5.88418203e-17,  -1.86517468e-16,   7.00828284e-17,
         3.03090886e-16,  -1.66533454e-17,   7.10542736e-17,
        -1.66533454e-16,   4.86277685e-16])

In [59]:
X_scaled.mean(axis=0).mean()

1.0526797687506115e-16

In [61]:
X_scaled.std(axis=0)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [43]:
X_train, X_test, y_train, y_test = sk.model_selection.train_test_split(
    X_scaled, pmtx, test_size=0.4, random_state=1)

In [44]:
# Create linear regression objectc
regr = linear_model.LinearRegression()

# Train the model using the training sets
regr.fit(X_train, y_train)

# The coefficients
print('Coefficients: \n', regr.coef_)
# The mean squared error
print("Mean squared error: %.2f"
      % np.mean((regr.predict(X_test) - y_test) ** 2))
# Explained variance score: 1 is perfect prediction
print('Variance score: %.2f' % regr.score(X_test, y_test))

Coefficients: 
 [[ -1.16321270e-01   3.82759545e-02   3.54522472e-02  -2.71379638e-02
    3.49357740e-02  -1.90305103e-02  -5.18060153e-02   1.02756139e-01
   -1.37969854e-01   1.01095033e-01  -3.91266879e-02   7.60528902e-02
    5.51004476e-02   1.01775935e-01]
 [  6.30174076e-01   1.05325032e-01   3.13711785e-01  -9.80375889e-02
    1.22008193e-01   2.98420226e-02   6.35731312e-02   6.56022225e-02
    2.81732309e-02  -8.58401572e-03   4.30040385e-02   1.76572278e-02
    9.44309239e-02  -1.16551095e-01]
 [ -2.41969294e-01   1.59266319e-01  -1.17011881e-01   1.23853912e-01
   -1.75449093e-02  -1.93158324e-02  -5.97403733e-02   1.57056638e-01
   -1.52252703e-01   9.63176327e-02  -6.08336845e-02   1.24778663e-01
   -1.13570706e-01   1.95232608e-01]
 [  1.19589016e-01   1.70008221e-01   7.57698369e-02  -1.59691993e-02
   -1.00311277e-01   4.04850070e-02  -2.45572550e-02   2.94105753e-02
    1.53449669e-02  -1.14509885e-02   2.23486532e-02   1.76078998e-02
    7.24180405e-02   6.01115230e-

In [64]:
y_test[0]

array([  3.32561690e-01,   4.32786774e-01,   1.98115883e-01,
         4.70694013e-03,   2.00000000e+00,   4.00000000e+00,
         1.30000000e+01,   2.20000000e+02,   3.95106641e+03,
         1.60000000e+01])

In [71]:
X_test[0]

array([ 1.01086499, -1.90257535, -0.26937053, -0.36982032,  0.42170525,
        1.26344082,  0.32565618, -0.63435796, -0.34336578,  1.15169182,
        0.46333517, -0.35546419, -0.22943205,  2.27780905])

In [70]:
regr.predict(X_test[0])

/Users/spacecoffin/Development/sprbrg/lib/python3.5/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([[  5.81091297e-01,   6.46632233e-01,   4.05079195e-01,
          3.24762723e-01,   1.28734484e+00,   1.97150205e+00,
          1.01313047e+01,   1.11999703e+03,   3.38978192e+03,
          1.60000000e+01]])

In [72]:
y_test[0]

array([  3.32561690e-01,   4.32786774e-01,   1.98115883e-01,
         4.70694013e-03,   2.00000000e+00,   4.00000000e+00,
         1.30000000e+01,   2.20000000e+02,   3.95106641e+03,
         1.60000000e+01])